### ISSUE TITLE
Incorrect vertical refresh rate?

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#1]
Hello,
Since it seems to have moved here, I'll drop my old issue in here.
Various online sources list the vertical refresh rate of Sega System 1 to be 60.0952 Hz (i.e. ~60.1 Hz), while the core uses a 61 Hz rate.
Which one is right?

**Comment by sorgelig** [comment]
New release has 60.1Hz

**Comment by Left-Empty** [comment]
Oh, wonderful!
