### ISSUE TITLE
Flicky - Super Players screen display issue

### ISSUE THREAD

**Issue by bibou42** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#16]
Before
SEGASYS1_20210121.rbf

![20210225_083734-screen](https://user-images.githubusercontent.com/18500303/109120815-b69b9e00-7746-11eb-93a7-a27894fc91cd.png)

After
SEGASYS1_20210218.rbf

![20210225_084034-screen](https://user-images.githubusercontent.com/18500303/109120836-c0bd9c80-7746-11eb-9ea5-9cf861fc89ca.png)

**Comment by sorgelig** [comment]
that happens in hiscore save/load commit it seems... 
@JimmyStones

**Comment by JimmyStones** [comment]
@sorgelig agreed, looking into it now, seems like it is trying to write hiscores to RAM even when an NVRAM dump hasn't been loaded

**Comment by bibou42** [comment]
Fixed, it was very fast. Thanks :)
