### ISSUE TITLE
controls broken on last release 20201115?

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#2]
I'm using a xb360 pad, and I'm not able to start games on SegaSys1 since last release (20201115)

Start button is reported to be 1 player, but it is actually adding more coins and nothing else. Tested all buttons on joypad.
Thanks

**Comment by sorgelig** [comment]
You need to update mra files. Make sure they are latest from this repository. Also re-define the buttons (or reset the buttons if you know how)

**Comment by jsmolina** [comment]
looks like old rbf was not deleted by issues while downloading 'main' vs 'master' branches.
thanks
