### ISSUE TITLE
Up'n'Down sprites offset for player 2

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#20]
When playing as player 2 the cars and flags are wrongly aligned with the roads :)

**Comment by JimmyStones** [comment]
@dfilskov The above update should have fixed this issue, please give it a test and let us know :)

**Comment by dfilskov** [comment]
I've run update_all - issue still seems to be there:
https://www.dropbox.com/s/whbyi66kh7ds5ai/up%27n%27down%202021-04-16%2016.57.mp4?dl=0
Couldn't see a "Update mode" setting in the OSD DIP Switches menu.

**Comment by JimmyStones** [comment]
I just changed the DIPs to be <switches default="FF,BE"> so upright mode is the default rather than cocktail - has your MRA not updated with that change?

**Comment by dfilskov** [comment]
Hmm doesn't seem to have helped :( - my MRA is from the 14th.

You can't repro?

**Comment by JimmyStones** [comment]
I could not, so I think it's probably because you've got DIPs already saved for that game with the old default - I've pushed a new update with the Cabinet DIP available - just add this to the switches section in the MRA if you want to test:

`<dip bits="8"   name="Cabinet" ids="Upright,Cocktail"/>`

**Comment by dfilskov** [comment]
YES - thank worked :) - thanks!
