### ISSUE TITLE
Food Fight - Defaults to Analog controls

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#32]
Default controls are analog and perhaps this should be changed to digital unless the user specifies.  Can seem uncontrollable when using a standard controller/arcade stick, otherwise.

**Comment by wwark** [comment]
@M-Walrus Food Fight is not in this core.
Or It is another game you made a reference ?

**Comment by M-Walrus** [comment]
sorry about that! I put in around 40 issue reports yesterday and must have got this one mixed up. porkchop already reported this in the correct repo- closing this.
