### ISSUE TITLE
Sega Ninja - Image shifted

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#33]
You will see with the screenshot.
![20210617_182831-screen](https://user-images.githubusercontent.com/469461/122437995-88aec380-cf9a-11eb-920f-ae68148e2f96.png)
Part of the river in the right is present on the left.
Thanks.

**Comment by wwark** [comment]
I checked the issue appeared when SEGASYS1 was ported on Mister-Devel.
The core on MrX-8B github page doesn't have this issue : https://github.com/MrX-8B/MiSTer-Arcade-SEGASYS1/raw/master/releases/Arcade-SEGASYS1_20200531.rbf

**Comment by sorgelig** [comment]
should be fixed now

**Comment by wwark** [comment]
Thank you for the quick fix.
It works great !
