### ISSUE TITLE
Arcade SegaSys1 update script not working

### ISSUE THREAD

**Issue by Zanza911** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#4]
Hello, 

when i run the update_all.sh script i got this error

Checking Arcade-SEGASYS1
URL: https://github.com/MiSTer-devel/Arcade-SEGASYS1_MiSTer
curl: (22) The requested URL returned error: 404 Not Found
Nothing to update

I read that it might be related to a change of the repository path in Git Hub for the new release,  can you please check this?

Thank you.

**Comment by sorgelig** [comment]
It has nothing to do with this core. Official updater script already updated to handle new repositories.
