### ISSUE TITLE
Bull Fight: missing second button

### ISSUE THREAD

**Issue by jeffgerstmann** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#7]
Sorry, I really should learn how to submit a fix of my own for simple stuff like this.

Bull Fight is missing its second button. First button is Sword, Second button is Wave Cape.

**Comment by bellwood420** [comment]
Modifying the line 15 in bullfight.mra like below will solve the issue.
How about making a pull request?

- before
`<buttons names="Fire,-,-,-,-,Start 1P,Start 2P,Coin" default="A,Start,Select,R"/>`
- after
`<buttons names="Sword,Wave Cape,-,-,-,Start 1P,Start 2P,Coin" default="A,B,Start,Select,R"/>`

**Comment by sorgelig** [comment]
fixed
