### ISSUE TITLE
4D Warriors: missing second button

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Arcade-SEGASYS1_MiSTer#8]
Hello,

In a similar way to Bullfight, 4D Warriors is missing its second button.

Simply editing the MRA's controls with a line such as this one
`<buttons names="Secondary Wide Shot,Fire,-,-,-,Start 1P,Start 2P,Coin" default="B,A,Start,Select,R"/>`
fixes it. I am unsure how to make pull requests and wouldn't want to mess things up, so I post it here.

Hurray for the MRA system, by the way!

Cheers,

**Comment by JimmyStones** [comment]
@Left-Empty @sorgelig This button is working in the latest release so this can be closed :)

**Comment by Left-Empty** [comment]
Oops, right, thanks, Boss of them all!
